server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Compresión GZIP (Buenas prácticas Cloud)
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    # 1. Servir la aplicación Angular (Frontend)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # 2. Proxy inverso para la API de Productos
    location /api/productos {
        # Usamos el resolver interno de Docker (127.0.0.11 en Compose, VPC DNS en ECS)
        # Esto evita que Nginx falle si el contenedor de la API aún no arranca.
        resolver 127.0.0.11 valid=30s;
        set $upstream_productos http://api-productos:3001;
        proxy_pass $upstream_productos;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 3. Proxy inverso para la API de Pedidos
    location /api/pedidos {
        resolver 127.0.0.11 valid=30s;
        set $upstream_pedidos http://api-pedidos:3002;
        proxy_pass $upstream_pedidos;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
